# Generated by Django 4.0.6 on 2022-09-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_of_birth', models.DateField()),
                ('employee_contact', models.CharField(max_length=15)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_designation', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('employee_image', models.ImageField(upload_to='')),
                ('password', models.CharField(default=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('occassion', models.CharField(max_length=50)),
            ],
        ),
    ]
