# Generated by Django 4.0.6 on 2022-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='holiday_over',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
